repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs<% if (testFramework == '1') { %>
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-lint<% } %><% if (testFramework == '2') { %>
  - repo: git://github.com/mattlqx/pre-commit-ruby
    rev: v1.3.5
    hooks:
      - id: rubocop<% } %>
